### ISSUE TITLE
Brightness issue 

### ISSUE THREAD

**Issue by pablotango** [mikefogg/SquareCamera#19]
Hi Mike, i want to thanks you for your support!
anyway i found another strange behavior, taking a picture with the same conditions (same position, same light, no HDR, no flash) with iphone camera and squarecamera has a different result in light perception. 
do you know if there is any settings in AVCaptureDevice to set exposure or brightness?

**Comment by pablotango** [comment]
i found the problem: is the AVCaptureSessionPresetHigh that is used for video, not for pictures, moving to AVCaptureSessionPresetPhoto or AVCaptureSessionPresetMedium solve the problem

**Comment by mikefogg** [comment]
Closing this as you can now select the photo quality you would like :)
