### ISSUE TITLE
2D Code detection

### ISSUE THREAD

**Issue by kosso** [mikefogg/SquareCamera#22]
Hi there,
btw, If you're interested in the functionality, I recently had a need for a QR code reader and all the modules I found needed the (old) zbar stuff or just didn't work right. But it turns out that since iOS 7, all this is built in. 

I discovered that to get this code detection running needed very much the same approach to this camera project, so I added it as an option so that while you are viewing your 'SquareCamera', you can optionally decided to have it fire a "code" event whenever it sees a 2D code (barcodes, QR codes, etc. etc.) with the value.

It's over here on my fork : https://github.com/kosso/SquareCamera

Particularly from [here](https://github.com/kosso/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L406)

And also the `AVCaptureMetadataOutputObjectsDelegate` which filters the metadata and sends the 'code' event [here](https://github.com/kosso/SquareCamera/blob/master/Classes/ComMfoggSquarecameraView.m#L547)

Let me know if you want a PR. 

Cheers!
K

**Comment by danny005** [comment]
Very nice! I was looking for a data matrix scanner and this module works much better than ti.barcode

**Comment by mikefogg** [comment]
@kosso Wow, completely missed this. That's a pretty sweet addition! Would you mind throwing together a pull request? Thanks again man!

**Comment by kosso** [comment]
Thanks. Yes, I was surprised to see so much built-in these day :)

**Comment by kosso** [comment]
I thought I already did! :)

**Comment by mikefogg** [comment]
@kosso Forgot to close this, thanks for the awesome addition!
