### ISSUE TITLE
Barcode scanning not working on 3.4.0 titanium SDK

### ISSUE THREAD

**Issue by moizchhatriwala** [mikefogg/SquareCamera#23]
I have compile the module for 3.4.0 sdk for iOS, but its not detecting the  simple barcode, can you let me know why it is happening, do you have any complied module supporting 3.4.0, if then can you please provide me the link to download it.

Regards,
Moiz

**Comment by danny005** [comment]
You have to download version 0.7 from Kossos repository:

https://github.com/kosso/SquareCamera/blob/master/dist/com.mfogg.squarecamera-iphone-0.7.zip

**Comment by mikefogg** [comment]
@moizchhatriwala Ah, I'll get on this. Currently it works well for me using Titanium 3.4.1 but I might not have uploaded that... I'll upload it now but in the meantime, @danny005 is right, @kosso's branch looks like it works already on 3.4.

**Comment by moizchhatriwala** [comment]
Hi,

It doesn't work on 3.4.0 or 3.4.1, this version of module is not detecting in tiapp.xml file.

But at last I was able to downgrade it and I have made it compatable to 3.4.0 sdk, and after setting some scanning barcode API it's started working fine for me.

If you want the compile version supporting 3.4.0 sdk then let me know.

Thanks & regards,
Moiz
