### ISSUE TITLE
Ability to unload the camera view

### ISSUE THREAD

**Issue by bitfabrikken** [mikefogg/SquareCamera#26]
Hello, thanks for an awesome module.

Would it be possible to have a function that actually closes the view and unloads it completely?

As it is now, removing the view from window and/or using pause and resume again and again, it seems it takes longer and longer to show the camera.

**Comment by mikefogg** [comment]
@bitfabrikken sorry this has taken so long! I'm sure you're long moved on from this issue :) If this is still a request, let me know and I can look into it!
