### ISSUE TITLE
How to use it in a landscape app?

### ISSUE THREAD

**Issue by m1ga** [mikefogg/SquareCamera#29]
I have an iPad app with orientationMode to landscape. When I click the scan button I open a new window like this:

```
var SquareCamera = require('com.mfogg.squarecamera'); // Initialize the SquareCamera module

        qrCodeWindow = Titanium.UI.createWindow({
            navBarHidden: true,
            exitOnClose: false,
            backgroundColor: 'black',
            width: '100%',
            height: '100%',
            fullscreen: true,
            orientationModes: [Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT]
        });

        var cameraTransform = Ti.UI.create2DMatrix();
        cameraTransform = cameraTransform.rotate(-90);

        var camera_view = SquareCamera.createView({
            top: 50,
            left:0,
            right:0,
            bottom:0,
            detectCodes: true, 
            backgroundColor: "#fff",
            frontQuality: SquareCamera.QUALITY_HIGH, // Optional Defaults to QUALITY_HIGH
            backQuality: SquareCamera.QUALITY_HD, // Optional Defaults to QUALITY_HD
            camera: "back", 
            transform:cameraTransform
        });

        camera_view.addEventListener("code", function(e){

            qrCodeWindow.close();

        });
        var btnClose = $.UI.create("Button", {
            classes: ["icon"],
            title: "\ue903",
            top: 10,
            right: 10
        })
        btnClose.addEventListener("click", onClickCloseQR);
        qrCodeWindow.add(btnClose);
        qrCodeWindow.add(camera_view);
        qrCodeWindow.open();
```

But the camera view is not in the top left corner and when I rotate the ipad the camera is upside down. Do I have to use the transform or is there a way to make the camera view rotate to the window orientation?

**Comment by m1ga** [comment]
Adding 
```c
// ------- rotate
        UIDeviceOrientation curDeviceOrientation = [[UIDevice currentDevice] orientation];
        
        float_t angle=0;
       
            angle=-M_PI/2;
            if ((long)curDeviceOrientation==4){
                angle = M_PI/2;
            }
        
        CATransform3D transform =  CATransform3DMakeRotation(angle, 0, 0, 1.0);
        self.prevLayer.transform =transform;
        curDeviceOrientation = nil;
      // --------
```

to ComMfoggSquarecameraView line 360 will show the camera in landscape. I'll try to add a parameter "forceHorizontal" to createView and make a pull request. Will take a bit though :)

**Comment by mikefogg** [comment]
@m1ga Hmm interesting! I have never used it in landscape mode so I really have no idea how it would work :) Let me play around with it, thanks for the code snippet! I'm curious, would you rather have it automatically detect when the phone is rotated and change accordingly, or set it on initialization?

**Comment by m1ga** [comment]
My app only works in landscape mode (ipad) and when you use autorotating and holding the ipad a little bit odd it will open the camera in potraitmode which is wrong in my case. So I need to set it to fixed landscape (left or right is ok)

**Comment by m1ga** [comment]
I've added a flag to turn it on https://github.com/mikefogg/SquareCamera/pull/30 
default is still off.

**Comment by mikefogg** [comment]
@m1ga little delayed here but thanks for the addition!
